Parichay.Mvc/Areas/Transactions/Controllers/SalesController.cs
using Newtonsoft.Json;
using Parichay.Bussiness.Model;
using Parichay.Service;
using Rotativa;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;

namespace Parichay.Mvc.Areas.Transactions.Controllers
{
    [ValidateSession]
    public class SalesController : Controller
    {
        private ISalesService _ISalesService;
        public SalesController(ISalesService ISalesService)
        {
            _ISalesService = ISalesService;
        }

        // GET: Transactions/Sales
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult PoopulateSales()
        {
            var result = _ISalesService.GetCustomer();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create(SalesViewModel model, int id)
        {
            //ViewBag.ModalAccesFor = "Sales";

            if (id == 0)
            {
                // New Add Form
                model.Id = id;
                return View(model);
            }
            else
            {
                model = _ISalesService.GetSerializedSalesBySalesId(id);
                //Edit Form
                return View(model);
            }

        }

        [HttpPost]
        public ActionResult CreateEditSales(SalesViewModel model)
        {
            var result = _ISalesService.AddSales(model);
            if (result.STATUS.Contains("SUCCESS"))
                return Json(new { success = true, Message = "ADDED" });
            else
                return Json(new { success = false, Message = "FAILED" });
        }

        [HttpPost]
        public ActionResult Delete(int id, string purpose, string passkey)
        {
            try
            {

                // VALIDATE WITH RIGHT SECURITYCODE
                if (_ISalesService.validateSecurityCode(purpose, passkey))
                {
                    //FINAL DELETE
                    var status = _ISalesService.DeleteCustomer(id);
                    return Json(new { success = true, Message = "DELETED" });
                }
                else
                {
                    return Json(new { success = false, ErrorMessage = "WRONGPASSKEY" });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, ErrorMessage = "Exception" });
            }
        }

        public ActionResult InvoicePDF()
        {
            var result = _ISalesService.GetSerializedSalesReportBySalesId(1);

            var salesItemList = JsonConvert.DeserializeObject<List<SALESITEMSERIALZED>>(result.SALESITEM);

            var Report = new ReportPDF
            {
                SALESITEMS = salesItemList,
                FULLNAME = result.FULLNAME,
                MOBILENUMBER = result.MOBILENUMBER,
                GSTNUMBER = result.GSTNUMBER,
                ADDRESSLINEONE = result.ADDRESSLINEONE,
                ADDRESSLINETWO = result.ADDRESSLINETWO,
                STATE = result.STATE,
                CITY = result.CITY,
                COUNTRY = result.COUNTRY,
                PINCODE = result.PINCODE,
                SALESDATE = result.SALESDATE,
                SALESID = result.SALESID,
                REMARKS = result.REMARKS,
                SALESAMOUNT = result.SALESAMOUNT,
                TAXSLAB = result.TAXSLAB,
                IGST = result.IGST,
                CGST = result.CGST,
                SGST = result.SGST,
                SALESAMOUNTGST = result.SALESAMOUNTGST
            };
            return View(Report);
        }

        [AllowAnonymous]
        
        public ActionResult InvoicePDFDownload(int id)
        {

            var result = _ISalesService.GetSerializedSalesReportBySalesId(id);

            var salesItemList = JsonConvert.DeserializeObject<List<SALESITEMSERIALZED>>(result.SALESITEM);

            var Report = new ReportPDF
            {
                SALESITEMS = salesItemList,
                FULLNAME = result.FULLNAME,
                MOBILENUMBER =result.MOBILENUMBER,
                GSTNUMBER = result.GSTNUMBER,
                ADDRESSLINEONE= result.ADDRESSLINEONE,
                ADDRESSLINETWO=result.ADDRESSLINETWO,
                STATE=result.STATE,
                CITY = result.CITY,
                COUNTRY = result.COUNTRY,
                PINCODE = result.PINCODE,
                SALESDATE = result.SALESDATE,
                SALESID = result.SALESID,
                REMARKS = result.REMARKS,
                SALESAMOUNT = result.SALESAMOUNT,
                TAXSLAB = result.TAXSLAB,
                IGST = result.IGST,
                CGST = result.CGST,
                SGST = result.SGST,
                SALESAMOUNTGST = result.SALESAMOUNTGST,
                DISCOUNT=result.DISCOUNT
            };


            ViewBag.ReportNameTitle= result.SALESID;



            Dictionary<string, string> cookieCollection = new Dictionary<string, string>();
            foreach (var key in Request.Cookies.AllKeys)
            {
                cookieCollection.Add(key, Request.Cookies.Get(key).Value);
            }
            string dir = "~/Areas/Transactions/Views/Sales/";
            string ext = ".cshtml";
            var filename = "INVOICE_" + result.SALESID + ".pdf";
            string fullpath = Path.Combine(Server.MapPath("~/temp"), filename);
            var file = new ViewAsPdf(dir + "InvoicePDF" + ext, Report)
            {
                FileName = result.SALESID,
                CustomSwitches = "--print-media-type",
                PageOrientation = Rotativa.Options.Orientation.Portrait,
                PageSize = Rotativa.Options.Size.A4,
                PageMargins = new Rotativa.Options.Margins(0, 0, 0, 0),
                PageWidth = 210,
                PageHeight = 297,
                Cookies = cookieCollection
               // IsGrayScale = true
            };
            var bytearray = file.BuildPdf(this.ControllerContext);
            var filestream = new FileStream(fullpath, FileMode.Create, FileAccess.Write);
            filestream.Write(bytearray, 0, bytearray.Length);
            filestream.Close();
            return Json(new { fileName = filename });
        }

        [HttpGet]
        [DeleteFile] //Action Filter, it will auto delete the file after download, 
        public ActionResult Download(string file)
        {
            string fullPath = Path.Combine(Server.MapPath("~/temp"), file);

            return File(fullPath, "application/pdf", file);
        }

        public JsonResult GetSalesIdByCustomerId(int customerId)
        {
            var result = _ISalesService.GetSalesIdListbyCustomerId(customerId);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

Parichay.Mvc/Areas/Transactions/Views/Sales/Create.cshtml
@using Parichay.Common
@model Parichay.Bussiness.Model.SalesViewModel
@{
    ViewBag.Title = "CREATE SALES";
    Layout = "~/Views/Shared/_LayoutPageDashboard.cshtml";

}
@section Scripts
{
    <script type="text/javascript" src="@Url.Content("~/Commonjs/Sales/SalesAddEdit.js")"></script>
}
<style>

    #Mytable td{
		text-transform:uppercase;
	}

    .btn {
        font-size: 1.0rem;
        font-weight: 500;
    }

    .app-page-title {
        padding: 10px;
        margin: -30px -30px 30px;
        position: relative;
    }

    .error {
        color: red;
    }


    
.add, .cut
{
	border-width: 1px;
	display: block;
	font-size: .8rem;
	padding: 0.25em 0.5em;	
	float: left;
	text-align: center;
	width: 1.6em;
}

    .add{
        background: #9AF;
        box-shadow: 0 1px 2px rgba(0,0,0,0.2);
        background-image: -moz-linear-gradient(#00ADEE 5%, #0078A5 100%);
        background-image: -webkit-linear-gradient(#00ADEE 5%, #0078A5 100%);
        border-radius: 0.5em;
        border-color: #0076A3;
        color: #FFF;
        cursor: pointer;
        font-weight: bold;
        text-shadow: 0 -1px 2px rgba(0,0,0,0.333);
    }

    .cut {
        background: #9AF;
        box-shadow: 0 1px 2px rgba(0,0,0,0.2);
        background-image: -moz-linear-gradient(#e80c16 5%, #dc10b0 100%);
        background-image: -webkit-linear-gradient(#e80c16 5%, #dc10b0 100%);
        border-radius: 0.5em;
        border-color: #0076A3;
        color: #FFF;
        cursor: pointer;
        font-weight: bold;
        text-shadow: 0 -1px 2px rgba(0,0,0,0.333);
    }

    /*.add { margin: -2.5em 0 0; }*/

    .add:hover {
        background: #00ADEE;
    }

    .cut {
        opacity: 0;
        position: relative;
        top: 0;
        left: -4.5em;
    }
    .cut {
        -webkit-transition: opacity 100ms ease-in;
    }

    tr:hover .cut {
        opacity: 1;
    }

    
table.balance { float: right; width: 15%;margin-right: 400px; }
table.balance:after { clear: both; content: ""; display: table; }

table.balance th, table.balance td { width: 0%; }
table.balance td { text-align: left; }


</style>
<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <a href="/Transactions/Sales" style="text-decoration:none">
                <div class="page-title-heading">
                    <div>
                            SALES
                        @if (Model.Id > 0)
                        {
                        <div class="page-title-subheading">
                            @Model.SalesId
                        </div>
                        }
                        

                    </div>
                </div>
            </a>

            <div class="page-title-actions">
                <div class="d-inline-block dropdown">
                    @Html.Hidden("RedirectToIndex", Url.Action("Index", "Sales"))
                    @if (Model.Id == 0)
                    {
                        <button class="mb-2 mr-2 btn btn-gradient-success" id="btn_SaveSales">SAVE</button>
                        <button class="mb-2 mr-2 btn btn-gradient-info" id="btn_ClearSales">CLEAR</button>
                    }
                    else
                    {
                        <button class="mb-2 mr-2 btn btn-gradient-success" id="btn_SaveSales">SAVE</button>
                        <button class="mb-2 mr-2 btn btn-gradient-info" id="btn_EditSales">EDIT</button>
                    }
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        <form id="FormSales">
            <div class="form-row">
                @Html.HiddenFor(x => x.Id)
                @Html.HiddenFor(x => x.CustomerId)
                @Html.HiddenFor(x => x.SalesItemGridSerialize)
                <div class="col-md-2">
                    <div class="position-relative form-group">
                        @Html.LabelSuperScriptFor(x => x.SalesDate, "BILL DATE", "*", new { @class = "" })
                        @if (Model.Id > 0)
                        {
                            @Html.TextBoxFor(x => x.SalesDate, new { @class = "form-control" })
                        }
                        else
                        {
                            @Html.TextBoxFor(x => x.SalesDate, new { @class = "form-control input-mask-trigger", data_toggle = "datepicker-sales", data_inputmask_alias = "datetime", data_inputmask_inputformat = "dd/mm/yyyy", im_insert = "false" })
                        }
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="position-relative form-group">
                        @Html.LabelSuperScriptFor(x => x.CustomerName, "CUSTOMER NAME", "*", new { @class = "" })
                        @Html.TextBoxFor(x => x.CustomerName, new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="position-relative form-group">
                        @Html.LabelSuperScriptFor(x => x.Discount, "DISCOUNT ₹", "", new { @class = "" })
                        @Html.TextBoxFor(x => x.Discount, new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="position-relative form-group">
                        @Html.LabelSuperScriptFor(x => x.Remarks, "REMARK", "", new { @class = "" })
                        @Html.TextBoxFor(x => x.Remarks, new { @class = "form-control" })
                    </div>
                </div>
                <div class="col-md-3">
                    @Html.LabelSuperScriptFor(x => x.TaxSlab, "TAX SLAB", "*", new { @class = "" })
                    <div class="position-relative form-group">
                        <div>
                            <div class="custom-checkbox custom-control custom-control-inline">
                                <label class="form-check-label">IGST</label>
                                @Html.RadioButtonFor(x => x.TaxSlab, "IGST", new { @class = "form-check-input" })


                            </div>
                            <div class="custom-checkbox custom-control custom-control-inline">
                                <label class="form-check-label">CGST-SGST</label>
                                @Html.RadioButtonFor(x => x.TaxSlab, "CGST-SGST", new { @class = "form-check-input" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <div class="row">
            <div class="col-lg-12">
                <div class="main-card mb-3 card">
                    <div class="card-body">
                        <h5 class="card-title">SALES ITEMS</h5>
                        <table class="inventory mb-0 table" id="myTableheadList">
                            <thead >
                                <tr>
                                    <th>#</th>
                                    <th id="ITEM">ITEM</th>
                                    <th id="WARRANTY">WARRANTY</th>
                                    <th id="HSN">HSN CODE</th>
                                    <th id="RATE">RATE</th>
                                    <th id="QUANTITY">QUANTITY</th>
                                    <th id="PRICE">PRICE</th>
                                </tr>
                            </thead>

                            <tbody id="Mytable">
                            </tbody>
                        </table>
                        <a class="add" style="color: white;">+</a>

                        <br /><br /><br /><br />

                        <table class="balance">
                            <tr>
                                <th><span>TOTAL</span></th>
                                <td><span data-prefix>&#8377; &nbsp;</span><span style="color: #406e80;font-family: fantasy;"></span></td>
                            </tr>
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Parichay.Mvc/Areas/Transactions/Views/Sales/Index.cshtml
@{
    ViewBag.Title = "SALES";
    Layout = "~/Views/Shared/_LayoutPageDashboard.cshtml";
}
@section Scripts
{
    <script type="text/javascript" src="@Url.Content("~/Commonjs/Sales/Sales.js")"></script>
}

<style>
    .btn {
        font-size: 1.0rem;
        font-weight: 500;
    }

    .app-page-title {
        padding: 10px;
        margin: -30px -30px 30px;
        position: relative;
    }

    .btn-icon .btn-icon-wrapper {
        margin-right: .5rem;
        margin-left: 0;
        margin-top: 0;
        font-size: 30px;
        vertical-align: middle;
        transition: color .1s;
        display: inline-block;
    }

    #MytableSales tr {
        text-transform: uppercase;
    }

    .has-error .help-block, .has-error .control-label, .has-error .radio, .has-error .checkbox, .has-error .radio-inline, .has-error .checkbox-inline {
        color: #a94442;
    }
</style>

<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>
                    SALES
                </div>
            </div>
            <div class="page-title-actions">
                <div class="d-inline-block dropdown">
                    <form action="Sales/create/0">
                        <button class="mb-2 mr-2 btn btn-gradient-primary">CREATE</button>
                    </form>

                </div>
            </div>
        </div>
    </div>

    <div class="card-body">
        <button id="ReloadGridSales" style="display:none">Modal</button>
        <button id="ClearGridSales" style="display:none">Modal</button>


        <div class="boxFAQ" id="questionMarkId">
            <div class="popover popover-custom fade bs-popover-auto" role="tooltip" id="popover594729" style="position: absolute;  top: 0px; left: 0px;" x-placement="right">
                <div class="arrow" style="top: 131px;"></div><h3 class="popover-header"></h3><div class="popover-body">
                    <div class="dropdown-menu-header">
                        <div class="dropdown-menu-header-inner bg-primary">
                            <div class="menu-header-image opacity-5" style="background-image: url('assets/images/dropdown-header/abstract2.jpg');"></div>
                            <div class="menu-header-content">
                                <h5 class="menu-header-title" id="lbl_fullname"></h5>
                                <h6 class="menu-header-subtitle" id="lbl_phoneNumber"></h6>
                            </div>
                        </div>
                    </div>
                    <ul class="nav flex-column">
                        <li class="nav-item-header nav-item">Activity</li>
                        <li class="nav-item-divider nav-item"></li>
                        <li class="nav-item"><a href="javascript:void(0);" class="nav-link" id="EditRow">EDIT</a></li>
                        <li class="nav-item"><a href="javascript:void(0);" class="nav-link" id="DeleteRow">DELETE</a></li>
                        <li class="nav-item"><a href="javascript:void(0);" class="nav-link" id="DownlaodPDF">DOWNLOAD PDF</a></li>
                        @Html.Hidden("RedirectTo", Url.Action("Create", "Sales", new { id = "__id__" }))
                    </ul>
                </div>
            </div>
        </div>




        <table style="width: 100%;" id="SalesTable" class="table table-hover table-striped table-bordered">
            <thead>
                <tr>
                    <th id="ID" style="display:none">ID</th>
                    <th id="SALEID">SALE ID</th>
                    <th id="SALEDATE">SALE DATE</th>
                    <th id="CUSTOMERNAME">CUSTOMER NAME</th>
                    <th id="AMOUNT">AMOUNT</th>
                    
                </tr>
            </thead>
            <tbody id="MytableSales">

                @*Load Table Content from ajax*@

            </tbody>
            <tfoot>
                <tr>
                    <th style="display:none">ID</th>
                    <th id="SALEID">SALE ID</th>
                    <th id="SALE DATE">SALE DATE</th>
                    <th id="CUSTOMER NAME">CUSTOMER NAME</th>
                    <th id="AMOUNT">AMOUNT</th>
                    
                </tr>
            </tfoot>
        </table>
    </div>

</div>